### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by poli39a1y** [Z3NTL3/TCP-Flood#1]
root@VmUbuntu20:~/TCP-Flood# python3 z3slam.py 1.1.1.1 10000 
It is required to use python 3.9+ version in order to run this script

**Comment by Z3NTL3** [comment]
> root@VmUbuntu20:~/TCP-Flood# python3 z3slam.py 1.1.1.1 10000 It is required to use python 3.9+ version in order to run this script

Hello,

You got this message due your python version is not 3.9+.

'randbytes' function from the random module in python was implemented in py version 3.9. Update your python to the newest version in order to solve.
